export const REQUEST = '_REQUEST';
export const SUCCESS = '_SUCCESS';
export const FAILURE = '_FAILURE';

export const AUTH_SIGN_UP = 'AUTH_SIGN_UP';
export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';
export const AUTH_FETCH_USER = 'AUTH_FETCH_USER';

export const PROFILE_CREATE = 'PROFILE_CREATE';
export const PROFILE_UPDATE = 'PROFILE_UPDATE';

export const PROFILE_MODAL_TOGGLE = 'PROFILE_MODAL_TOGGLE';

export const CATEGORIES_FETCH = 'CATEGORIES_FETCH';

export const PASSWORD_UPDATE = 'PASSWORD_UPDATE';
