export const REQUEST = '_REQUEST';
export const SUCCESS = '_SUCCESS';
export const FAILURE = '_FAILURE';

export const AUTH_SIGN_UP = 'AUTH_SIGN_UP';
export const AUTH_SIGN_IN = 'AUTH_SIGN_IN';
export const AUTH_FETCH_USER = 'AUTH_FETCH_USER';

export const PROFILE_CREATE = 'PROFILE_CREATE';
export const PROFILE_UPDATE = 'PROFILE_UPDATE';

export const PROFILE_MODAL_TOGGLE = 'PROFILE_MODAL_TOGGLE';

export const PASSWORD_UPDATE = 'PASSWORD_UPDATE';

export const CATEGORIES_FETCH = 'CATEGORIES_FETCH';
export const CATEGORIES_FETCH_ALL = 'CATEGORIES_FETCH_ALL';
export const CATEGORIES_EXPAND = 'CATEGORIES_EXPAND';
export const CATEGORIES_COLLAPSE = 'CATEGORIES_COLLAPSE';

export const APPLICATION_FETCH = 'APPLICATION_FETCH';
export const APPLICATIONS_ADD_TO_FAVORITES = 'APPLICATIONS_ADD_TO_FAVORITES';
export const APPLICATIONS_REMOVE_FROM_FAVORITES = 'APPLICATIONS_REMOVE_FROM_FAVORITES';

export const REVIEW_CREATE = 'REVIEW_CREATE';
