export const CURRENT_USER_SIGN_UP = 'CURRENT_USER_SIGN_UP';
export const CURRENT_USER_SIGN_UP_REQUEST = 'CURRENT_USER_SIGN_UP_REQUEST';
export const CURRENT_USER_SIGN_UP_SUCCESS = 'CURRENT_USER_SIGN_UP_SUCCESS';
export const CURRENT_USER_SIGN_UP_FAILURE = 'CURRENT_USER_SIGN_UP_FAILURE';
