export const CURRENT_USER_SIGN_UP = 'CURRENT_USER_SIGN_UP';
export const CURRENT_USER_SIGN_UP_REQUEST = 'CURRENT_USER_SIGN_UP_REQUEST';
export const CURRENT_USER_SIGN_UP_SUCCESS = 'CURRENT_USER_SIGN_UP_SUCCESS';
export const CURRENT_USER_SIGN_UP_FAILURE = 'CURRENT_USER_SIGN_UP_FAILURE';

export const CURRENT_USER_LOG_IN = 'CURRENT_USER_LOG_IN';
export const CURRENT_USER_LOG_IN_REQUEST = 'CURRENT_USER_LOG_IN_REQUEST';
export const CURRENT_USER_LOG_IN_SUCCESS = 'CURRENT_USER_LOG_IN_SUCCESS';
export const CURRENT_USER_LOG_IN_FAILURE = 'CURRENT_USER_LOG_IN_FAILURE';
