export const CURRENT_USER_SIGN_UP = 'CURRENT_USER_SIGN_UP';
export const CURRENT_USER_SIGN_UP_REQUEST = 'CURRENT_USER_SIGN_UP_REQUEST';
export const CURRENT_USER_SIGN_UP_SUCCESS = 'CURRENT_USER_SIGN_UP_SUCCESS';
export const CURRENT_USER_SIGN_UP_FAILURE = 'CURRENT_USER_SIGN_UP_FAILURE';

export const CURRENT_USER_GET_CREDENTIALS = 'CURRENT_USER_GET_CREDENTIALS';
export const CURRENT_USER_GET_CREDENTIALS_REQUEST = 'CURRENT_USER_GET_CREDENTIALS_REQUEST';
export const CURRENT_USER_GET_CREDENTIALS_SUCCESS = 'CURRENT_USER_GET_CREDENTIALS_SUCCESS';
export const CURRENT_USER_GET_CREDENTIALS_FAILURE = 'CURRENT_USER_GET_CREDENTIALS_FAILURE';

export const CURRENT_USER_GET_INFO = 'CURRENT_USER_GET_INFO';
export const CURRENT_USER_GET_INFO_REQUEST = 'CURRENT_USER_GET_INFO_REQUEST';
export const CURRENT_USER_GET_INFO_SUCCESS = 'CURRENT_USER_GET_INFO_SUCCESS';
export const CURRENT_USER_GET_INFO_FAILURE = 'CURRENT_USER_GET_INFO_FAILURE';
