export const PROFILE_CREATE = 'PROFILE_CREATE';
export const PROFILE_CREATE_REQUEST = 'PROFILE_CREATE_REQUEST';
export const PROFILE_CREATE_SUCCESS = 'PROFILE_CREATE_SUCCESS';
export const PROFILE_CREATE_FAILURE = 'PROFILE_CREATE_FAILURE';

export const PROFILE_MODAL_TOGGLE = 'PROFILE_MODAL_TOGGLE';

export const PROFILE_UPDATE = 'PROFILE_UPDATE';
export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAILURE = 'PROFILE_UPDATE_FAILURE';
